In [1]:
import numpy as np
lst1=[1,2,3]
array1 = np.array(lst1)

In [2]:

type(lst1)

list

In [3]:
type(array1)

numpy.ndarray

In [4]:
lst1

[1, 2, 3]

In [5]:
lst2 = [4,5,6]
array2 = np.array(lst2)

In [6]:
print(f"Adding two lists {lst1} and {lst2} together: {lst1+lst2}")

Adding two lists [1, 2, 3] and [4, 5, 6] together: [1, 2, 3, 4, 5, 6]


In [7]:
print(f"Adding two numpy arrays {array1} and {array2} together: {array1+array2}")

Adding two numpy arrays [1 2 3] and [4 5 6] together: [5 7 9]


In [8]:
print("array2 multiplied by array1: ",array1*array2)

array2 multiplied by array1:  [ 4 10 18]


In [9]:
print("array2 divided by array1: ",array2/array1)

array2 divided by array1:  [4.  2.5 2. ]


In [10]:
print("array2 raised to the power of array1: ",array2**array1)

array2 raised to the power of array1:  [  4  25 216]


In [11]:
# sine function
print("Sine: ",np.sin(array1))

Sine:  [0.84147098 0.90929743 0.14112001]


In [16]:
# logarithm
print("Natural logarithm: ",np.log(array1))
print("Natural logarithm: ",np.log(array2))

Natural logarithm:  [0.         0.69314718 1.09861229]
Natural logarithm:  [1.38629436 1.60943791 1.79175947]


In [17]:
print("Base-10 logarithm: ",np.log10(array1))
print("Base-10 logarithm: ",np.log10(array2))

Base-10 logarithm:  [0.         0.30103    0.47712125]
Base-10 logarithm:  [0.60205999 0.69897    0.77815125]


In [19]:
print("Base-2 logarithm: ",np.log2(array1))
print("Base-2 logarithm: ",np.log2(array2))

Base-2 logarithm:  [0.        1.        1.5849625]
Base-2 logarithm:  [2.         2.32192809 2.5849625 ]


In [20]:
# Exponential
print("Exponential: ",np.exp(array1))
print("Exponential: ",np.exp(array2))

Exponential:  [ 2.71828183  7.3890561  20.08553692]
Exponential:  [ 54.59815003 148.4131591  403.42879349]


In [21]:
print("A series of zeroes:",np.zeros(7))

A series of zeroes: [0. 0. 0. 0. 0. 0. 0.]


In [22]:
print("A series of ones:",np.ones(9))

A series of ones: [1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [23]:
print("A series of numbers:",np.arange(5,16))

A series of numbers: [ 5  6  7  8  9 10 11 12 13 14 15]


In [24]:
print("Numbers spaced apart by 2:",np.arange(0,11,2))

Numbers spaced apart by 2: [ 0  2  4  6  8 10]


In [25]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5))

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [26]:
print("Every 5th number from 30 in reverse order: ",np.arange(30,-1,-5))

Every 5th number from 30 in reverse order:  [30 25 20 15 10  5  0]


In [27]:
print("11 linearly spaced numbers between 1 and 5: ",np.linspace(1,5,11))

11 linearly spaced numbers between 1 and 5:  [1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]


In [32]:
# create a 2-D array
z = np.array([[1,2,3],[4,5,6]])

In [33]:
# print this 2-D array
print(z)
# check the dimension of numpy array z
print(z.ndim)

[[1 2 3]
 [4 5 6]]
2


In [34]:
# create a 3-D array
k = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [35]:
# print this 3-D array
print(k)
# check the dimension of numpy array k
print(k.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [36]:
# sort the array
p = np.array([7,5,8,6,9,1])
q = np.sort(p)
print(p)
print('-------')
print(q)

[7 5 8 6 9 1]
-------
[1 5 6 7 8 9]


In [37]:
# find square root of values of numpy array
p = np.array([4,9,16,25])
q = np.sqrt(p)
print(q)

[2. 3. 4. 5.]


In [38]:
#PANDAS
import pandas as pd

In [39]:
labels = ['a','b','c']
print ("Labels:", labels)

Labels: ['a', 'b', 'c']


In [40]:
my_data = [10,20,30]
arr = np.array(my_data)
print("My data:", my_data)

My data: [10, 20, 30]


In [41]:
d = {'a':10,'b':20,'c':30}
print("Dictionary:", d)

Dictionary: {'a': 10, 'b': 20, 'c': 30}


In [42]:
s1=pd.Series(data=my_data)
print(s1)

0    10
1    20
2    30
dtype: int64


In [43]:
s2=pd.Series(data=my_data, index=labels)
print(s2)

a    10
b    20
c    30
dtype: int64


In [44]:
s3=pd.Series(arr, labels)
print(s3)

a    10
b    20
c    30
dtype: int32


In [45]:
s4=pd.Series(d)
print(s4)

a    10
b    20
c    30
dtype: int64


In [47]:
matrix_data = np.random.randint(1,25,size=25).reshape(5,5)
row_labels = ['A','B','C','D','E']
column_headings = ['V','W','X','Y','Z']

In [48]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe data frame looks like\n",'-'*45, sep='')
print(df)


The data frame looks like
---------------------------------------------
    V   W   X   Y   Z
A   8  17  19  20   4
B  13   4  18  14   2
C   4  10  10   6   9
D  11   2  21  13  17
E  10   1  19  13  16


In [49]:
d={'a':[10,20],'b':[30,40],'c':[50,60]}
df2=pd.DataFrame(data=d,index=['X','Y'])
print(df2)

    a   b   c
X  10  30  50
Y  20  40  60


In [50]:
df = pd.read_csv('practice_dataset.csv')

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  32 non-null     int64  
 1   Date      31 non-null     object 
 2   Pulse     32 non-null     int64  
 3   Maxpulse  32 non-null     int64  
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB


In [52]:
df.describe()

Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [53]:
df.head()

Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [54]:
df.head(15)

Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3

In [55]:
df.tail()

Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [56]:
#Finding Correlation b/w col of dataset
df.corr()

C:\Users\Siddharth\AppData\Local\Temp\ipykernel_11716\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


Duration     Pulse  Maxpulse  Calories
Duration  1.000000  0.004410  0.049959 -0.114169
Pulse     0.004410  1.000000  0.276583  0.513186
Maxpulse  0.049959  0.276583  1.000000  0.357460
Calories -0.114169  0.513186  0.357460  1.000000

In [57]:
df.isnull()

Duration   Date  Pulse  Maxpulse  Calories
0      False  False  False     False     False
1      False  False  False     False     False
2      False  False  False     False     False
3      False  False  False     False     False
4      False  False  False     False     False
5      False  False  False     False     False
6      False  False  False     False     False
7      False  False  False     False     False
8      False  False  False     False     False
9      False  False  False     False     False
10     False  False  False     False     False
11     False  False  False     False     False
12     False  False  False     False     False
13     False  False  False     False     False
14     False  False  False     False     False
15     False  False  False     False     False
16     False  False  False     False     False
17     False  False  False     False     False
18     False  False  False     False      True
19     False  False  False     False     False
20     False  False  False     False     False
21     False  False  False     False     False
22     False   True  False     False     False
23     False  False  False     False     False
24     False  False  False     False     False
25     False  False  False     False     False
26     False  False  False     False     False
27     False  False  False     False     False
28     False  False  False     False      True
29     False  False  False     False     False
30     False  False  False     False     False
31     False  False  False     False     False

In [58]:
df.sample(7)

Duration          Date  Pulse  Maxpulse  Calories
16        60  '2020/12/16'     98       120     215.2
3         45  '2020/12/04'    109       175     282.4
28        60  '2020/12/28'    103       132       NaN
24        45  '2020/12/24'    105       132     246.0
19        60  '2020/12/19'    103       123     323.0
0         60  '2020/12/01'    110       130     409.1
13        60  '2020/12/13'    106       128     345.3

In [59]:
df.describe().transpose()

count      mean        std    min    25%    50%      75%    max
Duration   32.0   68.4375  70.039591   30.0   60.0   60.0   60.000  450.0
Pulse      32.0  103.5000   7.832933   90.0  100.0  102.5  106.500  130.0
Maxpulse   32.0  128.5000  12.998759  101.0  120.0  127.5  132.250  175.0
Calories   30.0  304.6800  66.003779  195.1  250.7  291.2  343.975  479.0

In [60]:
df.mean()

C:\Users\Siddharth\AppData\Local\Temp\ipykernel_11716\3698961737.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


Duration     68.4375
Pulse       103.5000
Maxpulse    128.5000
Calories    304.6800
dtype: float64

In [61]:
df.std()

C:\Users\Siddharth\AppData\Local\Temp\ipykernel_11716\3390915376.py:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.std()


Duration    70.039591
Pulse        7.832933
Maxpulse    12.998759
Calories    66.003779
dtype: float64

In [62]:
df.var()

C:\Users\Siddharth\AppData\Local\Temp\ipykernel_11716\1568254755.py:1: FutureWarning: The default value of numeric_only in DataFrame.var is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.var()


Duration    4905.544355
Pulse         61.354839
Maxpulse     168.967742
Calories    4356.498897
dtype: float64

In [68]:
df.min()


C:\Users\Siddharth\AppData\Local\Temp\ipykernel_11716\2316870759.py:1: FutureWarning: The default value of numeric_only in DataFrame.min is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.min()


Duration     30.0
Pulse        90.0
Maxpulse    101.0
Calories    195.1
dtype: float64

In [64]:
df.max()

C:\Users\Siddharth\AppData\Local\Temp\ipykernel_11716\1151452817.py:1: FutureWarning: The default value of numeric_only in DataFrame.max is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.max()


Duration    450.0
Pulse       130.0
Maxpulse    175.0
Calories    479.0
dtype: float64

In [65]:
df.min()

C:\Users\Siddharth\AppData\Local\Temp\ipykernel_11716\3962516015.py:1: FutureWarning: The default value of numeric_only in DataFrame.min is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.min()


Duration     30.0
Pulse        90.0
Maxpulse    101.0
Calories    195.1
dtype: float64

In [66]:
print("\n The 'Duration' column\n", '-'*25, sep = '')
print(df['Duration'])


 The 'Duration' column
-------------------------
0      60
1      60
2      60
3      45
4      45
5      60
6      60
7     450
8      30
9      60
10     60
11     60
12     60
13     60
14     60
15     60
16     60
17     60
18     45
19     60
20     45
21     60
22     45
23     60
24     45
25     60
26     60
27     60
28     60
29     60
30     60
31     60
Name: Duration, dtype: int64


In [67]:
print("\nType of the column: ", type(df['Duration']), sep='')


Type of the column: <class 'pandas.core.series.Series'>
